"""Compose the Mac App Store screenshots from the popover captures.

Same type as appstore-frames.py, turned landscape: Recursive Mono title,
Karla description, the same soft ground ramp.
Three frames mirror the iOS set -- inbox, message, keys -- and each hangs the
popover from the landing page's own menu bar (.mac-bar: Apple
mark, then bell, Wi-Fi, battery and clock, the glyphs read out of index.html
and the bell out of bell-body.svg and bell-clapper.svg), with the bell over
the popover's arrow. Output is 2560x1600, one of the sizes App Store Connect
accepts for macOS, written to fastlane/screenshots-macos/<locale>/.

The popover artwork comes from `make screens-mac`, which drives the real Mac
app and needs a human at the machine; it leaves the three raw captures in
/tmp/notifi-screens as mac-inbox.png, mac-detail.png and mac-keys.png.

    python3 apps/app/Scripts/appstore-frames-mac.py

Run it from the repo root. It renders every locale in one pass -- the caption
table in fastlane/screenshot-copy.json is generated by `make gen-copy`, and
en-US shares en-GB's English the way fastlane/metadata does.
"""
import json, os, sys
import random
from PIL import Image, ImageChops, ImageDraw, ImageFilter, ImageFont

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from publish_image import publish

REPO = os.environ.get("REPO", os.getcwd())
RAW = os.environ.get("RAW", "/tmp/notifi-screens")
ASSETS = f"{REPO}/apps/app/Shared/Assets.xcassets"

with open(f"{REPO}/apps/app/fastlane/screenshot-copy.json") as fh:
    CAPTIONS = json.load(fh)

W, H = 2560, 1600
# The iOS frames' light ground on the right of the split; the red field on
# the left carries its own white ink, and the popover its own dark one.
FG, MUTED, BRAND = "#0A0A0A", "#5A5A5A", "#BC2122"
GROUND_TOP, GROUND_BOTTOM = (0xE8, 0xE8, 0xEB), (0xFC, 0xFC, 0xFD)
BRAND_RGB = (0xBC, 0x21, 0x22)
FG_RGB = (0x0A, 0x0A, 0x0A)
GUTTER = 170
TITLE_SIZE, DESC_SIZE = 108, 54
# The red field owns the left of the page and the popover the right; the
# split is fixed so every locale's frame lines up on the listing.
POPOVER_CENTER_X = 1910
POPOVER_H = 1320
SCALE = POPOVER_H / 1452
# The bar is the landing page's .mac-bar, whose sizes are container-query
# units of the desk the popover hangs in (the popover is 94% of that desk).
# One cqw here is one percent of that desk, so the bar and every glyph on it
# keep the site's proportions against the popover.
CQW = (972 * SCALE / 0.94) / 100
BAR_H = round(5.83 * CQW)
SITE = f"{REPO}/apps/api/public"
SYSTEM_FONT = "/System/Library/Fonts/SFNS.ttf"

# The banner is drawn in Apple's own macOS UI kit and exported from Figma --
# see .claude/skills/notification-mockup. It is a mockup because the alternative
# is photographing a real banner, which lasts about five seconds and takes the
# desk behind it with it.
BANNER = f"{REPO}/apps/app/Scripts/assets/notification-banner.png"
# A macOS banner is 344pt wide and the popover is 461pt, the width index.html
# gives .mac-shot. Sizing the banner against the popover rather than the frame
# keeps the pair at the ratio a real screen shows them at, whatever POPOVER_H
# is set to.
BANNER_PT, POPOVER_PT = 344, 461
# Where the system puts it: under the bar, in from the right edge.
BANNER_TOP_PT, BANNER_RIGHT_PT = 8, 12

# The fourth field says whether a banner is laid over the popover. Only the
# first frame gets one -- it is the shot that has to say what the app does, and
# on the other two the banner would cover the thing being shown.
FRAMES = [
    ("mac-inbox.png", "inboxTitleIpad", "inboxBody", "01_inbox.png", True),
    ("mac-detail.png", "messageTitle", "messageBody", "02_message.png", False),
    ("mac-keys.png", "keysTitle", "keysBody", "03_keys.png", False),
]


def dehinted(name, out_dir):
    """Same fix as appstore-frames.py: both brand fonts carry TrueType hinting
    FreeType renders wrong at these sizes, and at 40px+ the hints buy nothing."""
    from fontTools.ttLib import TTFont
    from fontTools.ttLib.tables import ttProgram

    out = f"{out_dir}/.{name}.ttf"
    font = TTFont(f"{REPO}/apps/app/Shared/Fonts/{name}.ttf")
    for table in ("fpgm", "prep", "cvt ", "gasp"):
        if table in font:
            del font[table]
    glyf = font["glyf"]
    for glyph_name in glyf.keys():
        glyph = glyf[glyph_name]
        if hasattr(glyph, "program"):
            empty = ttProgram.Program()
            empty.fromBytecode(b"")
            glyph.program = empty
    font.save(out)
    return out


def wrap(draw, text, font, width):
    lines, line = [], ""
    for word in text.split():
        trial = f"{line} {word}".strip()
        if draw.textlength(trial, font=font) <= width or not line:
            line = trial
        else:
            lines.append(line)
            line = word
    if line:
        lines.append(line)
    return lines


def ground(popover_box):
    ramp = Image.new("RGB", (1, H))
    px = ramp.load()
    for y in range(H):
        t = y / (H - 1)
        px[0, y] = tuple(
            round(a + (b - a) * t) for a, b in zip(GROUND_TOP, GROUND_BOTTOM)
        )
    page = ramp.resize((W, H), Image.BICUBIC).convert("RGBA")

    bloom = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(bloom).ellipse(
        [popover_box[0] - 220, popover_box[3] - 260,
         popover_box[2] + 220, popover_box[3] + 200],
        fill=BRAND_RGB + (26,),
    )
    page.alpha_composite(bloom.filter(ImageFilter.GaussianBlur(160)))
    return page


def load_popover(name):
    path = f"{RAW}/{name}"
    if not os.path.exists(path):
        sys.exit(f"{path} is missing -- run `make screens-mac` first")
    shot = Image.open(path).convert("RGBA")
    # The capture carries its own shape in the alpha channel -- rounded panel
    # plus the arrow -- so no rounding or bezel ring is drawn here.
    return shot.resize((round(shot.width * SCALE), POPOVER_H), Image.LANCZOS)


def rasterize(svg, width, tint, out_dir, name):
    """rsvg-convert renders an SVG string at a pixel width; the result is
    used as a mask and filled with the tint, which is what the site's CSS
    mask-image does with the same files."""
    import subprocess
    path = f"{out_dir}/.{name}.png"
    subprocess.run(["rsvg-convert", "-w", str(width), "-o", path],
                   input=svg.encode(), check=True)
    art = Image.open(path).convert("RGBA")
    os.remove(path)
    layer = Image.new("RGBA", art.size, tint + (0,))
    layer.putalpha(art.getchannel("A"))
    return layer


def site_svg(cls):
    """The bar's marks are the landing page's own: the inline SVGs the
    .mac-apple, .mac-wifi and .mac-batt classes carry in index.html."""
    import re
    html = open(f"{SITE}/index.html").read()
    m = re.search(rf'<svg class="{cls}"[^>]*>.*?</svg>', html, re.S)
    if not m:
        sys.exit(f"index.html no longer carries an <svg class=\"{cls}\">")
    svg = m.group(0).replace('fill="currentColor"', 'fill="#fff"')
    svg = svg.replace('stroke="currentColor"', 'stroke="#fff"')
    return svg.replace("<svg ", '<svg xmlns="http://www.w3.org/2000/svg" ', 1)


def bell(out_dir):
    """The site's .bell: bell-body.svg and bell-clapper.svg stacked, both
    cropped by the same box by generate-marks.sh."""
    size = round(3.7 * CQW)
    icon = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    for part in ("bell-body", "bell-clapper"):
        layer = rasterize(open(f"{SITE}/{part}.svg").read(), size, FG_RGB, out_dir, part)
        icon.alpha_composite(layer, (0, (size - layer.height) // 2))
    return icon


def slide_arrow(popover, to_x):
    """screens-mac.sh does the same for the site: the arrow sits wherever the
    screen edge pushed it, and the panel's top edge is uniform, so the arrow
    can be moved along it seamlessly to sit under the bell."""
    alpha = popover.getchannel("A").load()
    w, h = popover.size

    def span(y):
        xs = [x for x in range(w) if alpha[x, y] > 8]
        return (min(xs), max(xs)) if xs else None

    apex_y = next(y for y in range(h) if span(y))
    panel_top = next(y for y in range(apex_y, h)
                     if (sp := span(y)) and sp[1] - sp[0] > w * 0.5)
    ax0, ax1 = span(panel_top - 1)
    pad = 10
    # The panel's own first row carries the junction with the arrow, baked in
    # where the arrow met it, so it travels with the arrow; the row it leaves
    # behind is repaired with a stretch of plain panel edge from beside it.
    box = (ax0 - pad, apex_y, ax1 + pad + 1, panel_top + 1)
    arrow = popover.crop(box)
    width = box[2] - box[0]
    clean_x = box[0] - width - 30 if box[0] - width - 30 > 0 else box[2] + 30
    edge = popover.crop((clean_x, panel_top, clean_x + width, panel_top + 1))
    # The arrow is translucent, so the capture baked the wallpaper behind it
    # into its colour. Only its solid core is repainted with the panel's own
    # colour; the soft edge is the window's shadow and is left as captured.
    panel = popover.getpixel(((ax0 + ax1) // 2, panel_top + 4))[:3]
    alpha_band = arrow.getchannel("A")
    core = alpha_band.point(lambda v: 255 if v > 200 else 0)
    arrow = Image.composite(Image.new("RGBA", arrow.size, panel + (255,)),
                            arrow, core)
    arrow.putalpha(alpha_band)
    moved = popover.copy()
    moved.paste((0, 0, 0, 0), box)
    moved.paste(edge, (box[0], panel_top))
    dx = round(to_x - (ax0 + ax1 + 1) / 2)
    moved.paste(arrow, (box[0] + dx, box[1]), arrow)
    return moved, panel_top


def menu_bar(canvas, desk, out_dir):
    """The site's .mac-bar across the top of the popover: frosted white over
    the ground, the Apple mark at the
    left, and .mac-status right-aligned -- bell, Wi-Fi, battery, clock.
    Returns the bell's centre x, which the popover's arrow then meets."""
    x0, y0, x1, _ = desk
    width = x1 - x0
    bar = Image.new("RGBA", (width, BAR_H), (255, 255, 255, 170))
    canvas.alpha_composite(bar, (x0, y0))
    d = ImageDraw.Draw(canvas)

    pad = round(2.9 * CQW)
    apple = rasterize(site_svg("mac-apple"), round(5.06 * CQW), FG_RGB, out_dir, "apple")
    apple.putalpha(apple.getchannel("A").point(lambda v: v * 85 // 100))
    canvas.alpha_composite(apple, (x0 + pad, y0 + (BAR_H - apple.height) // 2))

    gap = round(2.85 * CQW)
    icon = bell(out_dir)
    wifi = rasterize(site_svg("mac-wifi"), round(4.6 * CQW), FG_RGB, out_dir, "wifi")
    batt = rasterize(site_svg("mac-batt"), round(6.44 * CQW), FG_RGB, out_dir, "batt")
    clock = ImageFont.truetype(SYSTEM_FONT, round(3.13 * CQW))
    try:
        clock.set_variation_by_name("Medium")
    except OSError:
        pass
    text = "Sat 29 Aug 14:07"
    tb = d.textbbox((0, 0), text, font=clock)
    cluster = (icon.width + gap + wifi.width + gap + batt.width + gap
               + (tb[2] - tb[0]))

    x = x1 - pad - cluster
    bell_x = x + icon.width / 2
    canvas.alpha_composite(icon, (x, y0 + (BAR_H - icon.height) // 2))
    x += icon.width + gap
    canvas.alpha_composite(wifi, (x, y0 + (BAR_H - wifi.height) // 2))
    x += wifi.width + gap
    canvas.alpha_composite(batt, (x, y0 + (BAR_H - batt.height) // 2))
    x += batt.width + gap
    d.text((x, y0 + (BAR_H - (tb[3] - tb[1])) // 2 - tb[1]), text, font=clock, fill=FG)
    return bell_x


def banner(canvas, desk, popover_w):
    """Lay the notification over the popover's top right, where the system
    draws it -- a banner is above everything, so it covers the inbox's first
    rows rather than making room in them."""
    if not os.path.exists(BANNER):
        sys.exit(f"{BANNER} is missing -- see .claude/skills/notification-mockup")
    art = Image.open(BANNER).convert("RGBA")

    # The export carries its drop shadow, so its edges are not the banner's.
    # The opaque core is measured rather than written down: re-exporting at a
    # different scale changes the padding, and a hard-coded inset would move
    # the banner instead of failing.
    core = art.getchannel("A").point(lambda v: 255 if v > 200 else 0).getbbox()
    if not core:
        sys.exit(f"{BANNER} has no opaque core -- is it the right file?")
    core_w = core[2] - core[0]

    px_per_pt = popover_w / POPOVER_PT
    scale = (BANNER_PT * px_per_pt) / core_w
    art = art.resize((round(art.width * scale), round(art.height * scale)),
                     Image.LANCZOS)

    # Position by the core's edges, not the image's, so the shadow hangs
    # outside the margin the way it does on screen.
    right = desk[2] - round(BANNER_RIGHT_PT * px_per_pt)
    top = desk[1] + BAR_H + round(BANNER_TOP_PT * px_per_pt)
    canvas.alpha_composite(
        art,
        (right - round(core[2] * scale), top - round(core[1] * scale)),
    )


SPLIT = 1200
RED_RGB = (0xBC, 0x21, 0x22)
MARK = 150


def frame(locale, captions, title_key, desc_key, popover, out_dir, out_name,
          with_banner):
    # The bar and the popover, nothing around them: the desk is the site's
    # .mac-desk width so the bar keeps its proportions, but it carries no
    # border and no ground below the popover. Centred on the right half.
    desk_w = round(popover.width / 0.94)
    desk_h = BAR_H + popover.height
    desk_x = POPOVER_CENTER_X - desk_w // 2
    desk_y = (H - desk_h) // 2
    desk = [desk_x, desk_y, desk_x + desk_w, desk_y + desk_h]
    left = desk_x + (desk_w - popover.width) // 2
    top = desk_y + BAR_H
    box = [left, top, left + popover.width, top + popover.height]

    canvas = ground(box)
    d = ImageDraw.Draw(canvas)
    # The left field is the brand red, edge to edge, carrying the mark and
    # the caption in white; the popover keeps the light ground on the right.
    # The grain is the site's: noise seeded so the field is the same every
    # run, overlaid at half strength so it reads as paper, not as dither.
    random.seed(7)
    field = Image.new("RGB", (SPLIT, H), RED_RGB)
    # Drawn at half size and doubled: a one-pixel grain at 2560 wide is gone
    # the moment the listing scales the frame down.
    grain = Image.effect_noise((SPLIT // 2, H // 2), 26)
    # Only the specks above the midpoint are kept, so the field is flecked
    # lighter and never darker.
    grain = grain.point(lambda v: max(v, 128))
    grain = grain.resize((SPLIT, H), Image.NEAREST).convert("RGB")
    field = ImageChops.overlay(field, grain)
    canvas.paste(field, (0, 0))

    mono = dehinted("RecursiveMono-SemiBold", out_dir)
    sans = dehinted("Karla", out_dir)

    tf = ImageFont.truetype(mono, TITLE_SIZE)
    try:
        tf.set_variation_by_name("Bold")
    except OSError:
        pass
    df = ImageFont.truetype(sans, DESC_SIZE)
    try:
        df.set_variation_by_name("Regular")
    except OSError:
        pass

    mark = Image.new("RGBA", (MARK, MARK), (0, 0, 0, 0))
    for part in ("bell-body", "bell-clapper"):
        layer = rasterize(open(f"{SITE}/{part}.svg").read(), MARK, (255, 255, 255), out_dir, part)
        mark.alpha_composite(layer, (0, (MARK - layer.height) // 2))

    title_lines = []
    for para in captions[title_key].split("\n"):
        title_lines += wrap(d, para, tf, SPLIT - GUTTER * 2)
    desc_lines = wrap(d, captions[desc_key], df, SPLIT - GUTTER * 2)
    block_h = (MARK + 64
               + len(title_lines) * round(TITLE_SIZE * 1.14)
               + 56
               + len(desc_lines) * round(DESC_SIZE * 1.48))
    y = (H - block_h) // 2
    canvas.alpha_composite(mark, (GUTTER, y))
    y += MARK + 64
    for line in title_lines:
        d.text((GUTTER, y), line, font=tf, fill="#FFFFFF")
        y += round(TITLE_SIZE * 1.14)
    y += 56
    for line in desc_lines:
        d.text((GUTTER, y), line, font=df, fill=(255, 222, 222))
        y += round(DESC_SIZE * 1.48)

    bell_x = menu_bar(canvas, desk, out_dir)

    popover, panel_row = slide_arrow(popover, bell_x - left)

    # .mac-wall .mac-shot: drop-shadow(0 18px 36px rgba(0,0,0,.55)), at 2x,
    # following the popover's own alpha, arrow and all.
    # Cast from the panel alone, not the arrow: blurred by 36 the arrow's own
    # shadow rises above the panel edge and haloes the arrow.
    shadow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    silhouette = Image.new("RGBA", popover.size, (18, 18, 24, 96))
    body = popover.getchannel("A").point(lambda v: v * 96 // 255)
    body.paste(0, (0, 0, popover.width, panel_row))
    silhouette.putalpha(body)
    shadow.alpha_composite(silhouette, (left, top + 36))
    canvas.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(36)))
    canvas.alpha_composite(popover, (left, top))

    if with_banner:
        banner(canvas, desk, popover.width)

    publish(canvas.convert("RGB"), f"{out_dir}/{out_name}", "PNG")

    for tmp in (mono, sans):
        os.remove(tmp)


popovers = {raw: load_popover(raw) for raw, _, _, _, _ in FRAMES}
for locale, caption_key in [("en-US", "en-GB"), ("en-GB", "en-GB"),
                            ("de-DE", "de-DE"), ("es-ES", "es-ES"),
                            ("fr-FR", "fr-FR"), ("it", "it")]:
    out_dir = f"{REPO}/apps/app/fastlane/screenshots-macos/{locale}"
    os.makedirs(out_dir, exist_ok=True)
    stale = f"{out_dir}/01_popover.png"
    if os.path.exists(stale):
        os.remove(stale)
    for raw, title_key, desc_key, out_name, with_banner in FRAMES:
        frame(locale, CAPTIONS[caption_key], title_key, desc_key,
              popovers[raw], out_dir, out_name, with_banner)
