"""Compose the Mac App Store screenshots from the popover capture.

Same visual language as appstore-frames.py, turned landscape: Recursive Mono
title, Karla description, one red accent, a soft ground ramp, and the popover
floating on it. Output is 2560x1600, one of the sizes App Store Connect
accepts for macOS, written to fastlane/screenshots-macos/<locale>/.

The popover artwork comes from `make screens-mac`, which drives the real Mac
app and needs a human at the machine. This script prefers the raw capture that
run leaves at /tmp/notifi-screens/mac.png and falls back to the committed site
asset apps/api/public/screens/mac-cut.webp, so the store frames can be
re-rendered without recapturing.

    python3 apps/app/Scripts/appstore-frames-mac.py

Run it from the repo root. It renders every locale in one pass -- the caption
table in fastlane/screenshot-copy.json is generated by `make gen-copy`, and
en-US shares en-GB's English the way fastlane/metadata does.
"""
import json, os, sys
from PIL import Image, ImageDraw, ImageFilter, ImageFont

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from publish_image import publish

REPO = os.environ.get("REPO", os.getcwd())
RAW = "/tmp/notifi-screens/mac.png"
FALLBACK = f"{REPO}/apps/api/public/screens/mac-cut.webp"

with open(f"{REPO}/apps/app/fastlane/screenshot-copy.json") as fh:
    CAPTIONS = json.load(fh)

W, H = 2560, 1600
FG, MUTED, BRAND = "#0A0A0A", "#5A5A5A", "#BC2122"
GROUND_TOP, GROUND_BOTTOM = (0xE8, 0xE8, 0xEB), (0xFC, 0xFC, 0xFD)
BRAND_RGB = (0xBC, 0x21, 0x22)
GUTTER = 170
TITLE_SIZE, DESC_SIZE = 108, 54
RULE_W, RULE_H = 190, 9
# The caption owns the left half of the page and the popover the right; the
# split is fixed so every locale's frame lines up on the listing.
TEXT_W = 1150
POPOVER_CENTER_X = 1910


def dehinted(name, out_dir):
    """Same fix as appstore-frames.py: both brand fonts carry TrueType hinting
    FreeType renders wrong at these sizes, and at 40px+ the hints buy nothing."""
    from fontTools.ttLib import TTFont
    from fontTools.ttLib.tables import ttProgram

    out = f"{out_dir}/.{name}.ttf"
    font = TTFont(f"{REPO}/apps/app/Shared/Fonts/{name}.ttf")
    for table in ("fpgm", "prep", "cvt ", "gasp"):
        if table in font:
            del font[table]
    glyf = font["glyf"]
    for glyph_name in glyf.keys():
        glyph = glyf[glyph_name]
        if hasattr(glyph, "program"):
            empty = ttProgram.Program()
            empty.fromBytecode(b"")
            glyph.program = empty
    font.save(out)
    return out


def wrap(draw, text, font, width):
    lines, line = [], ""
    for word in text.split():
        trial = f"{line} {word}".strip()
        if draw.textlength(trial, font=font) <= width or not line:
            line = trial
        else:
            lines.append(line)
            line = word
    if line:
        lines.append(line)
    return lines


def ground(popover_box):
    ramp = Image.new("RGB", (1, H))
    px = ramp.load()
    for y in range(H):
        t = y / (H - 1)
        px[0, y] = tuple(
            round(a + (b - a) * t) for a, b in zip(GROUND_TOP, GROUND_BOTTOM)
        )
    page = ramp.resize((W, H), Image.BICUBIC).convert("RGBA")

    bloom = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(bloom).ellipse(
        [popover_box[0] - 220, popover_box[3] - 260,
         popover_box[2] + 220, popover_box[3] + 200],
        fill=BRAND_RGB + (26,),
    )
    page.alpha_composite(bloom.filter(ImageFilter.GaussianBlur(160)))
    return page


def load_popover():
    src = RAW if os.path.exists(RAW) else FALLBACK
    shot = Image.open(src).convert("RGBA")
    # The capture carries its own shape in the alpha channel -- rounded panel
    # plus the arrow -- so no rounding or bezel ring is drawn here. Scaled to a
    # fixed height so every locale frames the identical popover.
    target_h = 1320
    target_w = round(shot.width * target_h / shot.height)
    return shot.resize((target_w, target_h), Image.LANCZOS), src


def frame(locale, captions, popover, out_dir):
    left = POPOVER_CENTER_X - popover.width // 2
    top = (H - popover.height) // 2
    box = [left, top, left + popover.width, top + popover.height]

    canvas = ground(box)
    d = ImageDraw.Draw(canvas)

    mono = dehinted("RecursiveMono-SemiBold", out_dir)
    sans = dehinted("Karla", out_dir)

    tf = ImageFont.truetype(mono, TITLE_SIZE)
    try:
        tf.set_variation_by_name("Bold")
    except OSError:
        pass
    df = ImageFont.truetype(sans, DESC_SIZE)
    try:
        df.set_variation_by_name("Regular")
    except OSError:
        pass

    # Measure the caption first so the block centres on the page vertically,
    # which is what a landscape frame wants where the portrait one stacks.
    title_lines = []
    for para in captions.get("inboxTitleIpad", captions["inboxTitle"]).split("\n"):
        title_lines += wrap(d, para, tf, TEXT_W)
    desc_lines = wrap(d, captions["inboxBody"], df, TEXT_W)
    block_h = (len(title_lines) * round(TITLE_SIZE * 1.14)
               + 34 + RULE_H + 34
               + len(desc_lines) * round(DESC_SIZE * 1.48))
    y = (H - block_h) // 2

    for line in title_lines:
        d.text((GUTTER, y), line, font=tf, fill=FG)
        y += round(TITLE_SIZE * 1.14)
    y += 34
    d.rounded_rectangle([GUTTER, y, GUTTER + RULE_W, y + RULE_H],
                        radius=RULE_H // 2, fill=BRAND)
    y += RULE_H + 34
    for line in desc_lines:
        d.text((GUTTER, y), line, font=df, fill=MUTED)
        y += round(DESC_SIZE * 1.48)

    if GUTTER + TEXT_W > box[0] - 60:
        print(f"WARNING {locale}: caption column runs into the popover")

    shadow = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(shadow).rounded_rectangle(
        [box[0] + 26, box[1] + 54, box[2] - 26, box[3] + 30],
        radius=36, fill=(18, 18, 24, 96),
    )
    canvas.alpha_composite(shadow.filter(ImageFilter.GaussianBlur(46)))
    canvas.alpha_composite(popover, (left, top))

    publish(canvas.convert("RGB"), f"{out_dir}/01_popover.png", "PNG")

    for tmp in (mono, sans):
        os.remove(tmp)


popover, src = load_popover()
print(f"popover source: {src}")
for locale, caption_key in [("en-US", "en-GB"), ("en-GB", "en-GB"),
                            ("de-DE", "de-DE"), ("es-ES", "es-ES"),
                            ("fr-FR", "fr-FR"), ("it", "it")]:
    out_dir = f"{REPO}/apps/app/fastlane/screenshots-macos/{locale}"
    os.makedirs(out_dir, exist_ok=True)
    frame(locale, CAPTIONS[caption_key], popover, out_dir)
